-- Named executable transaction templates, not one script to execute end to end.
-- Bind all :parameters via the driver. Never interpolate client text into SQL.
-- Preconditions: per-session serial lock + authenticated binding; exact API/content/policy validation;
-- same idempotency key returns previous receipt before stale-version checks; catch-up committed separately.
-- On ANY statement/COMMIT error the caller MUST ROLLBACK. CHECK(0) means stale/invalid precondition.
-- JSON event/projection/snapshot/input/hash values are generated by their owning builders, not copied from a client.
-- The reference profile is review-only; normal mode is gated by approved policy.

-- name: accept_investigation
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(
 SELECT 1 FROM sessions WHERE session_id=:session_id AND run_epoch=:run_epoch
 AND state_version=:expected_version AND scene_id=:scene_id
 AND lifecycle='running' AND phase IN ('decision','coordinating')
) THEN 1 ELSE 0 END;
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,reason_code,mission_ms,created_at_ms)
SELECT session_id,:reservation_id,account_id,:task_id,'reserve','available',1,-1,1,0,account_version,'REPORT_TASK_ACCEPTED',:mission_ms,:now_ms FROM quota_accounts WHERE session_id=:session_id AND account_id=:report_account_id;
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,reason_code,mission_ms,created_at_ms)
SELECT session_id,:resource_charge_id,account_id,:task_id,'spend','available',1,-1,0,1,account_version,'INVESTIGATION_ACCEPTED',:mission_ms,:now_ms FROM quota_accounts WHERE session_id=:session_id AND account_id=:resource_account_id;
INSERT INTO task_requests(session_id,task_id,scene_id,commander_binding_id,target_role,task_kind,topic_id,target_id,option_id,status,report_reservation_id,accepted_mission_ms,due_mission_ms,created_at_ms)
VALUES(:session_id,:task_id,:scene_id,:commander_binding_id,:target_role,'investigate_and_report',:topic_id,:target_id,:option_id,'running',:reservation_id,:mission_ms,:due_mission_ms,:now_ms);
INSERT INTO investigations(session_id,investigation_id,task_id,scene_id,role,option_id,resource_key,resource_charge_id,status,accepted_mission_ms,due_mission_ms)
VALUES(:session_id,:investigation_id,:task_id,:scene_id,:target_role,:option_id,:resource_key,:resource_charge_id,'running',:mission_ms,:due_mission_ms);
INSERT INTO events(session_id,seq,event_id,kind,mission_ms,state_version,actor_kind,binding_id,request_id,payload_json,recorded_at_ms)
SELECT session_id,last_event_seq+1,:event_id,'task.accepted',:mission_ms,state_version+1,'human',:commander_binding_id,:request_id,:event_data_json,:now_ms FROM sessions WHERE session_id=:session_id;
INSERT INTO view_events(session_id,view_role,cursor,source_seq,event_type,public_payload_json)
SELECT :session_id,'commander',COALESCE(MAX(cursor),0)+1,(SELECT last_event_seq FROM sessions WHERE session_id=:session_id),:public_event_type,:public_event_json FROM view_events WHERE session_id=:session_id AND view_role='commander';
INSERT INTO decision_snapshots(session_id,snapshot_id,scene_id,binding_id,snapshot_kind,source_seq,mission_ms,state_version,snapshot_hash,snapshot_json)
SELECT session_id,:snapshot_id,:scene_id,:commander_binding_id,'task',last_event_seq,:mission_ms,state_version+1,:snapshot_hash,:snapshot_json FROM sessions WHERE session_id=:session_id;
UPDATE sessions SET state_version=state_version+1,mission_ms=:mission_ms,anchor_monotonic_ms=:anchor_ms,updated_at_ms=:now_ms,phase='coordinating' WHERE session_id=:session_id;
INSERT INTO commands(session_id,request_id,run_epoch,binding_id,command_kind,payload_hash,accepted_state_version,response_status,response_json,accepted_at_ms)
SELECT session_id,:request_id,run_epoch,:commander_binding_id,'task.create',:command_hash,state_version,202,:response_json,:now_ms FROM sessions WHERE session_id=:session_id;
COMMIT;
-- end

-- name: complete_investigation
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(
 SELECT 1 FROM investigations i JOIN sessions s USING(session_id)
 WHERE i.session_id=:session_id AND i.investigation_id=:investigation_id
 AND i.status='running' AND i.due_mission_ms<=:mission_ms AND s.scene_id=i.scene_id
 AND s.lifecycle='running' AND s.state_version=:expected_version
) THEN 1 ELSE 0 END;
UPDATE investigations SET status='completed',finished_mission_ms=:mission_ms WHERE session_id=:session_id AND investigation_id=:investigation_id;
INSERT INTO evidence_instances(session_id,instance_id,revision,scene_id,owner_role,private_definition_id,observation_type,acquired_mission_ms,observed_mission_ms,acquisition_investigation_id,public_payload_json,payload_hash)
SELECT session_id,:instance_id,1,scene_id,role,:private_definition_id,:observation_type,:mission_ms,:observed_mission_ms,investigation_id,:card_json,:card_hash FROM investigations WHERE session_id=:session_id AND investigation_id=:investigation_id;
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,parent_entry_id,reason_code,mission_ms,created_at_ms)
SELECT t.session_id,:report_charge_id,q.account_id,t.task_id,'spend','reserved',1,0,-1,1,q.account_version,t.report_reservation_id,'REPORT_COMPLETED',:mission_ms,:now_ms
FROM task_requests t JOIN quota_ledger l ON l.session_id=t.session_id AND l.entry_id=t.report_reservation_id JOIN quota_accounts q ON q.session_id=l.session_id AND q.account_id=l.account_id WHERE t.session_id=:session_id AND t.task_id=:task_id;
INSERT INTO reports(session_id,report_id,scene_id,sender_role,source_instance_id,source_revision,actor_binding_id,task_id,charge_entry_id,reported_mission_ms,immutable_payload_json,immutable_payload_hash)
SELECT session_id,:report_id,scene_id,owner_role,instance_id,revision,:npc_binding_id,:task_id,:report_charge_id,:mission_ms,public_payload_json,payload_hash FROM evidence_instances WHERE session_id=:session_id AND instance_id=:instance_id AND revision=1;
UPDATE task_requests SET status='completed',completed_at_ms=:now_ms WHERE session_id=:session_id AND task_id=:task_id;
INSERT INTO events(session_id,seq,event_id,kind,mission_ms,state_version,actor_kind,binding_id,request_id,payload_json,recorded_at_ms)
SELECT session_id,last_event_seq+1,:event_id,'report.created',:mission_ms,state_version+1,'npc',:npc_binding_id,:request_id,:event_data_json,:now_ms FROM sessions WHERE session_id=:session_id;
INSERT INTO view_events(session_id,view_role,cursor,source_seq,event_type,public_payload_json)
SELECT :session_id,'commander',COALESCE(MAX(cursor),0)+1,(SELECT last_event_seq FROM sessions WHERE session_id=:session_id),:public_event_type,:public_event_json FROM view_events WHERE session_id=:session_id AND view_role='commander';
INSERT INTO decision_snapshots(session_id,snapshot_id,scene_id,binding_id,snapshot_kind,source_seq,mission_ms,state_version,snapshot_hash,snapshot_json)
SELECT session_id,:snapshot_id,:scene_id,:npc_binding_id,'report',last_event_seq,:mission_ms,state_version+1,:snapshot_hash,:snapshot_json FROM sessions WHERE session_id=:session_id;
INSERT INTO public_records(session_id,public_record_id,revision,view_role,record_kind,source_seq,public_payload_json)
SELECT session_id,:public_record_id,1,'commander','report',last_event_seq,:report_view_json FROM sessions WHERE session_id=:session_id;
UPDATE sessions SET state_version=state_version+1,mission_ms=:mission_ms,anchor_monotonic_ms=:anchor_ms,updated_at_ms=:now_ms WHERE session_id=:session_id;
COMMIT;
-- end

-- name: upload_batch
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(
 SELECT 1 FROM sessions WHERE session_id=:session_id AND run_epoch=:run_epoch
 AND state_version=:expected_version AND scene_id=:scene_id
 AND lifecycle='running' AND phase IN ('decision','coordinating')
) THEN 1 ELSE 0 END;
-- refs_json is server-normalized [{uploadId,reportId,revision}]; client cannot choose uploadId.
INSERT INTO tx_assert SELECT CASE WHEN json_type(:refs_json)='array' AND json_array_length(:refs_json) BETWEEN 1 AND 5 THEN 1 ELSE 0 END;
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,reason_code,mission_ms,created_at_ms)
SELECT session_id,:upload_charge_id,account_id,:request_id,'spend','available',json_array_length(:refs_json),-json_array_length(:refs_json),0,json_array_length(:refs_json),account_version,'COMMANDER_UPLOAD',:mission_ms,:now_ms FROM quota_accounts WHERE session_id=:session_id AND account_id=:upload_account_id;
INSERT INTO uploads(session_id,upload_id,scene_id,report_id,report_revision,charge_entry_id,authorization_binding_id,uploaded_mission_ms)
SELECT :session_id,json_extract(value,'$.uploadId'),:scene_id,json_extract(value,'$.reportId'),json_extract(value,'$.revision'),:upload_charge_id,:commander_binding_id,:mission_ms FROM json_each(:refs_json);
-- Build immutable exact allowlisted prompt first in memory. Membership includes all current scene uploads for this cumulative reference profile.
INSERT INTO input_manifest_members(session_id,manifest_id,upload_id)
SELECT session_id,:manifest_id,upload_id FROM uploads WHERE session_id=:session_id AND scene_id=:scene_id;
-- Optional statement_refs_json is [] when no authorized free-text statements are included.
INSERT INTO manifest_statements(session_id,manifest_id,statement_id)
SELECT :session_id,:manifest_id,value FROM json_each(:statement_refs_json);
INSERT INTO input_manifests(session_id,manifest_id,scene_id,inbox_version,context_version,context_epoch,background_hash,input_hash,permitted_input_json,created_at_ms)
SELECT session_id,:manifest_id,:scene_id,inbox_version+1,assistant_context_version+1,:context_epoch,:background_hash,:input_hash,:advisor_input_json,:now_ms FROM sessions WHERE session_id=:session_id;
UPDATE agent_jobs SET status='superseded',updated_at_ms=:now_ms WHERE session_id=:session_id AND agent_role='advisor' AND status IN ('queued','running');
INSERT INTO agent_jobs(session_id,job_id,agent_role,scene_id,manifest_id,status,mode,input_hash,config_hash,input_version,inbox_version,context_version,deadline_at_ms,created_at_ms,updated_at_ms)
SELECT session_id,:job_id,'advisor',:scene_id,:manifest_id,'queued',:agent_mode,:input_hash,:config_hash,assistant_context_version+1,inbox_version+1,assistant_context_version+1,:job_deadline_at_ms,:now_ms,:now_ms FROM sessions WHERE session_id=:session_id;
INSERT INTO tx_assert SELECT CASE WHEN json_array_length(:upload_events_json)=json_array_length(:refs_json) AND (SELECT last_event_seq FROM sessions WHERE session_id=:session_id)=:base_event_seq THEN 1 ELSE 0 END;
INSERT INTO events(session_id,seq,event_id,kind,mission_ms,state_version,actor_kind,binding_id,request_id,payload_json,recorded_at_ms)
SELECT :session_id,:base_event_seq+CAST(j.key AS INTEGER)+1,json_extract(j.value,'$.eventId'),'upload.created',:mission_ms,:expected_version+1,'human',:commander_binding_id,:request_id,json_extract(j.value,'$.data'),:now_ms FROM json_each(:upload_events_json) j ORDER BY CAST(j.key AS INTEGER);
INSERT INTO view_events(session_id,view_role,cursor,source_seq,event_type,public_payload_json)
SELECT :session_id,'commander',COALESCE(MAX(cursor),0)+1,(SELECT last_event_seq FROM sessions WHERE session_id=:session_id),:public_event_type,:public_event_json FROM view_events WHERE session_id=:session_id AND view_role='commander';
INSERT INTO decision_snapshots(session_id,snapshot_id,scene_id,binding_id,snapshot_kind,source_seq,mission_ms,state_version,snapshot_hash,snapshot_json)
SELECT session_id,:snapshot_id,:scene_id,:commander_binding_id,'upload',last_event_seq,:mission_ms,state_version+1,:snapshot_hash,:snapshot_json FROM sessions WHERE session_id=:session_id;
UPDATE sessions SET inbox_version=inbox_version+1,assistant_context_version=assistant_context_version+1 WHERE session_id=:session_id;
UPDATE sessions SET state_version=state_version+1,mission_ms=:mission_ms,anchor_monotonic_ms=:anchor_ms,updated_at_ms=:now_ms WHERE session_id=:session_id;
INSERT INTO commands(session_id,request_id,run_epoch,binding_id,command_kind,payload_hash,accepted_state_version,response_status,response_json,accepted_at_ms)
SELECT session_id,:request_id,run_epoch,:commander_binding_id,'upload.create',:command_hash,state_version,200,:response_json,:now_ms FROM sessions WHERE session_id=:session_id;
COMMIT;
-- end

-- name: accept_operation
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(
 SELECT 1 FROM sessions WHERE session_id=:session_id AND run_epoch=:run_epoch
 AND state_version=:expected_version AND scene_id=:scene_id
 AND lifecycle='running' AND phase IN ('decision','coordinating')
) THEN 1 ELSE 0 END;
-- release_entries_json lists the outstanding current-scene task reservations; WAIT must pass [].
INSERT INTO tx_assert SELECT CASE WHEN :operation_kind!='wait' OR json_array_length(:release_entries_json)=0 THEN 1 ELSE 0 END;
UPDATE investigations SET status='cancelled',finished_mission_ms=:mission_ms,failure_code='SCENE_LEFT' WHERE session_id=:session_id AND scene_id=:scene_id AND status IN ('queued','running') AND :operation_kind='action';
UPDATE task_requests SET status='cancelled',completed_at_ms=:now_ms,failure_code='SCENE_LEFT' WHERE session_id=:session_id AND scene_id=:scene_id AND status IN ('accepted','running') AND :operation_kind='action';
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,parent_entry_id,reason_code,mission_ms,created_at_ms)
SELECT :session_id,json_extract(j.value,'$.entryId'),q.account_id,json_extract(j.value,'$.entryId'),'release','reserved',json_extract(j.value,'$.amount'),json_extract(j.value,'$.amount'),-json_extract(j.value,'$.amount'),0,q.account_version,json_extract(j.value,'$.parentEntryId'),'SCENE_LEFT',:mission_ms,:now_ms
FROM json_each(:release_entries_json) j JOIN quota_ledger p ON p.session_id=:session_id AND p.entry_id=json_extract(j.value,'$.parentEntryId') JOIN quota_accounts q ON q.session_id=p.session_id AND q.account_id=p.account_id WHERE :operation_kind='action';
INSERT INTO tx_assert SELECT CASE WHEN :operation_kind='wait' OR NOT EXISTS(SELECT 1 FROM quota_accounts WHERE session_id=:session_id AND scene_id=:scene_id AND reserved>0) THEN 1 ELSE 0 END;
INSERT INTO operations(session_id,operation_id,scene_id,operation_kind,action_id,status,private_plan_json,public_progress_json,accepted_mission_ms,due_mission_ms,created_at_ms)
VALUES(:session_id,:operation_id,:scene_id,:operation_kind,:action_id,'running',:private_plan_json,:public_progress_json,:mission_ms,:due_mission_ms,:now_ms);
INSERT INTO events(session_id,seq,event_id,kind,mission_ms,state_version,actor_kind,binding_id,request_id,payload_json,recorded_at_ms)
SELECT session_id,last_event_seq+1,:event_id,'action.committed',:mission_ms,state_version+1,'human',:commander_binding_id,:request_id,:event_data_json,:now_ms FROM sessions WHERE session_id=:session_id;
INSERT INTO view_events(session_id,view_role,cursor,source_seq,event_type,public_payload_json)
SELECT :session_id,'commander',COALESCE(MAX(cursor),0)+1,(SELECT last_event_seq FROM sessions WHERE session_id=:session_id),:public_event_type,:public_event_json FROM view_events WHERE session_id=:session_id AND view_role='commander';
INSERT INTO decision_snapshots(session_id,snapshot_id,scene_id,binding_id,snapshot_kind,source_seq,mission_ms,state_version,snapshot_hash,snapshot_json)
SELECT session_id,:snapshot_id,:scene_id,:commander_binding_id,'action',last_event_seq,:mission_ms,state_version+1,:snapshot_hash,:snapshot_json FROM sessions WHERE session_id=:session_id;
-- WAIT is resolving in-place; an action is travelling. mission_ms is sampled elapsed time, never += authored duration.
UPDATE sessions SET phase=CASE WHEN :operation_kind='wait' THEN 'resolving' ELSE 'travelling' END WHERE session_id=:session_id;
UPDATE sessions SET state_version=state_version+1,mission_ms=:mission_ms,anchor_monotonic_ms=:anchor_ms,updated_at_ms=:now_ms WHERE session_id=:session_id;
INSERT INTO commands(session_id,request_id,run_epoch,binding_id,command_kind,payload_hash,accepted_state_version,response_status,response_json,accepted_at_ms)
SELECT session_id,:request_id,run_epoch,:commander_binding_id,'action.create',:command_hash,state_version,202,:response_json,:now_ms FROM sessions WHERE session_id=:session_id;
COMMIT;
-- end

-- name: claim_model_attempt
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(SELECT 1 FROM agent_jobs WHERE session_id=:session_id AND job_id=:job_id AND status='queued' AND mode='live_model' AND deadline_at_ms>:now_ms) THEN 1 ELSE 0 END;
UPDATE agent_jobs SET status='running',updated_at_ms=:now_ms WHERE session_id=:session_id AND job_id=:job_id;
INSERT INTO agent_attempts(session_id,job_id,attempt_no,request_key,status,sent_at_ms)
SELECT :session_id,:job_id,COALESCE(MAX(attempt_no),0)+1,:provider_request_key,'sending',:now_ms FROM agent_attempts WHERE session_id=:session_id AND job_id=:job_id;
COMMIT;
-- Only after COMMIT: call the provider using stored immutable input. No network inside transaction.
-- end

-- name: seal_session
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(SELECT 1 FROM sessions WHERE session_id=:session_id AND lifecycle IN ('briefing','running') AND state_version=:expected_version) THEN 1 ELSE 0 END;
-- Due effects were already committed by catch-up. This transaction cancels remaining work, not completed observations.
UPDATE investigations SET status='cancelled',finished_mission_ms=:mission_ms,failure_code=:termination_reason WHERE session_id=:session_id AND status IN ('queued','running');
UPDATE task_requests SET status='cancelled',completed_at_ms=:now_ms,failure_code=:termination_reason WHERE session_id=:session_id AND status IN ('accepted','running');
UPDATE operations SET status='cancelled',completed_at_ms=:now_ms WHERE session_id=:session_id AND status IN ('accepted','running');
UPDATE agent_jobs SET status='cancelled',updated_at_ms=:now_ms WHERE session_id=:session_id AND agent_role='advisor' AND status IN ('queued','running');
-- release_entries_json contains one server-generated UUID and remaining amount per unfulfilled reservation.
-- Seal guard refuses COMMIT if any reservation remains; channel charges are deliberately not refunded.
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,parent_entry_id,reason_code,mission_ms,created_at_ms)
SELECT :session_id,json_extract(j.value,'$.entryId'),q.account_id,json_extract(j.value,'$.entryId'),'release','reserved',json_extract(j.value,'$.amount'),json_extract(j.value,'$.amount'),-json_extract(j.value,'$.amount'),0,q.account_version,json_extract(j.value,'$.parentEntryId'),'TERMINAL_CANCEL',:mission_ms,:now_ms
FROM json_each(:release_entries_json) j JOIN quota_ledger p ON p.session_id=:session_id AND p.entry_id=json_extract(j.value,'$.parentEntryId') JOIN quota_accounts q ON q.session_id=p.session_id AND q.account_id=p.account_id;
INSERT INTO events(session_id,seq,event_id,kind,mission_ms,state_version,actor_kind,request_id,payload_json,recorded_at_ms)
SELECT session_id,last_event_seq+1,:event_id,'session.sealed',:mission_ms,state_version+1,'rules',:request_id,:event_data_json,:now_ms FROM sessions WHERE session_id=:session_id;
INSERT INTO view_events(session_id,view_role,cursor,source_seq,event_type,public_payload_json)
SELECT :session_id,'commander',COALESCE(MAX(cursor),0)+1,(SELECT last_event_seq FROM sessions WHERE session_id=:session_id),'session.sealed',:public_event_json FROM view_events WHERE session_id=:session_id AND view_role='commander';
INSERT INTO terminal_seals(session_id,seal_id,sealed_hash,terminal_lifecycle,terminal_seq,terminal_state_version,terminal_mission_ms,outcome_json,immutable_behavior_json,content_hash,policy_hash,sealed_at_ms)
SELECT session_id,:seal_id,:sealed_hash,:terminal_lifecycle,last_event_seq,state_version+1,:mission_ms,:outcome_json,:behavior_json,content_hash,policy_hash,:now_ms FROM sessions WHERE session_id=:session_id;
UPDATE sessions SET terminal_seal_id=:seal_id,lifecycle=:terminal_lifecycle,phase='terminal',state_version=state_version+1,mission_ms=:mission_ms,anchor_monotonic_ms=NULL,updated_at_ms=:now_ms WHERE session_id=:session_id;
COMMIT;
-- end

-- name: accept_report_request
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(
 SELECT 1 FROM sessions WHERE session_id=:session_id AND run_epoch=:run_epoch
 AND state_version=:expected_version AND scene_id=:scene_id
 AND lifecycle='running' AND phase IN ('decision','coordinating')
) THEN 1 ELSE 0 END;
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,reason_code,mission_ms,created_at_ms)
SELECT session_id,:reservation_id,account_id,:task_id,'reserve','available',1,-1,1,0,account_version,'REPORT_TASK_ACCEPTED',:mission_ms,:now_ms FROM quota_accounts WHERE session_id=:session_id AND account_id=:report_account_id;
INSERT INTO task_requests(session_id,task_id,scene_id,commander_binding_id,target_role,task_kind,topic_id,target_id,option_id,status,report_reservation_id,accepted_mission_ms,due_mission_ms,created_at_ms)
VALUES(:session_id,:task_id,:scene_id,:commander_binding_id,:target_role,'request_report',:topic_id,:target_id,NULL,'running',:reservation_id,:mission_ms,:due_mission_ms,:now_ms);
INSERT INTO events(session_id,seq,event_id,kind,mission_ms,state_version,actor_kind,binding_id,request_id,payload_json,recorded_at_ms)
SELECT session_id,last_event_seq+1,:event_id,'task.accepted',:mission_ms,state_version+1,'human',:commander_binding_id,:request_id,:event_data_json,:now_ms FROM sessions WHERE session_id=:session_id;
INSERT INTO view_events(session_id,view_role,cursor,source_seq,event_type,public_payload_json)
SELECT :session_id,'commander',COALESCE(MAX(cursor),0)+1,(SELECT last_event_seq FROM sessions WHERE session_id=:session_id),:public_event_type,:public_event_json FROM view_events WHERE session_id=:session_id AND view_role='commander';
INSERT INTO decision_snapshots(session_id,snapshot_id,scene_id,binding_id,snapshot_kind,source_seq,mission_ms,state_version,snapshot_hash,snapshot_json)
SELECT session_id,:snapshot_id,:scene_id,:commander_binding_id,'task',last_event_seq,:mission_ms,state_version+1,:snapshot_hash,:snapshot_json FROM sessions WHERE session_id=:session_id;
UPDATE sessions SET state_version=state_version+1,mission_ms=:mission_ms,anchor_monotonic_ms=:anchor_ms,updated_at_ms=:now_ms,phase='coordinating' WHERE session_id=:session_id;
INSERT INTO commands(session_id,request_id,run_epoch,binding_id,command_kind,payload_hash,accepted_state_version,response_status,response_json,accepted_at_ms)
SELECT session_id,:request_id,run_epoch,:commander_binding_id,'task.create',:command_hash,state_version,202,:response_json,:now_ms FROM sessions WHERE session_id=:session_id;
COMMIT;
-- end

-- name: complete_report_request
BEGIN IMMEDIATE;
CREATE TEMP TABLE IF NOT EXISTS tx_assert(ok INTEGER NOT NULL CHECK(ok=1));
DELETE FROM tx_assert;
INSERT INTO tx_assert SELECT CASE WHEN EXISTS(
 SELECT 1 FROM task_requests t JOIN sessions s USING(session_id)
 WHERE t.session_id=:session_id AND t.task_id=:task_id AND t.task_kind='request_report'
 AND t.status IN ('accepted','running') AND t.due_mission_ms<=:mission_ms
 AND s.scene_id=t.scene_id AND s.lifecycle='running' AND s.state_version=:expected_version
) THEN 1 ELSE 0 END;
INSERT INTO quota_ledger(session_id,entry_id,account_id,operation_id,entry_kind,source_bucket,amount,delta_available,delta_reserved,delta_spent,account_version_before,parent_entry_id,reason_code,mission_ms,created_at_ms)
SELECT t.session_id,:report_charge_id,q.account_id,t.task_id,'spend','reserved',1,0,-1,1,q.account_version,t.report_reservation_id,'REPORT_COMPLETED',:mission_ms,:now_ms
FROM task_requests t JOIN quota_ledger l ON l.session_id=t.session_id AND l.entry_id=t.report_reservation_id JOIN quota_accounts q ON q.session_id=l.session_id AND q.account_id=l.account_id WHERE t.session_id=:session_id AND t.task_id=:task_id;
INSERT INTO reports(session_id,report_id,scene_id,sender_role,source_instance_id,source_revision,actor_binding_id,task_id,charge_entry_id,reported_mission_ms,immutable_payload_json,immutable_payload_hash)
SELECT session_id,:report_id,scene_id,owner_role,instance_id,revision,:npc_binding_id,:task_id,:report_charge_id,:mission_ms,public_payload_json,payload_hash FROM evidence_instances WHERE session_id=:session_id AND instance_id=:instance_id AND revision=:evidence_revision;
UPDATE task_requests SET status='completed',completed_at_ms=:now_ms WHERE session_id=:session_id AND task_id=:task_id;
INSERT INTO events(session_id,seq,event_id,kind,mission_ms,state_version,actor_kind,binding_id,request_id,payload_json,recorded_at_ms)
SELECT session_id,last_event_seq+1,:event_id,'report.created',:mission_ms,state_version+1,'npc',:npc_binding_id,:request_id,:event_data_json,:now_ms FROM sessions WHERE session_id=:session_id;
INSERT INTO view_events(session_id,view_role,cursor,source_seq,event_type,public_payload_json)
SELECT :session_id,'commander',COALESCE(MAX(cursor),0)+1,(SELECT last_event_seq FROM sessions WHERE session_id=:session_id),:public_event_type,:public_event_json FROM view_events WHERE session_id=:session_id AND view_role='commander';
INSERT INTO decision_snapshots(session_id,snapshot_id,scene_id,binding_id,snapshot_kind,source_seq,mission_ms,state_version,snapshot_hash,snapshot_json)
SELECT session_id,:snapshot_id,:scene_id,:npc_binding_id,'report',last_event_seq,:mission_ms,state_version+1,:snapshot_hash,:snapshot_json FROM sessions WHERE session_id=:session_id;
INSERT INTO public_records(session_id,public_record_id,revision,view_role,record_kind,source_seq,public_payload_json)
SELECT session_id,:public_record_id,1,'commander','report',last_event_seq,:report_view_json FROM sessions WHERE session_id=:session_id;
UPDATE sessions SET state_version=state_version+1,mission_ms=:mission_ms,anchor_monotonic_ms=:anchor_ms,updated_at_ms=:now_ms WHERE session_id=:session_id;
COMMIT;
-- end
