// GENERATED by contracts/generate_types.py. Do not edit.
// Runtime constraints and conditional branches are enforced by JSON Schema, not TS.

export type EvidenceRef = { "instanceId": string; "revision": number };

export type Citation = { "kind": "evidence" | "background" | "statement"; "refId": string; "revision": number };

export type KnownSourceEdge = { "fromRef": EvidenceRef; "toRef": EvidenceRef; "relation": "reported_from" | "same_source_confirmed" | "possibly_related"; "findingRef": (EvidenceRef | null) };

export type Evidence = { "instanceId": string; "revision": number; "sceneId": "E1" | "E2" | "E3"; "observationType": "direct_observation" | "official_statement" | "witness_statement" | "provenance_finding" | "correction" | "historical_image"; "text": string; "sourceLabel": string; "observationAgeMs": (number | null); "freshness": "current" | "historical" | "superseded" | "unknown"; "scope": string; "limitations": ReadonlyArray<string>; "knownSourceEdges": ReadonlyArray<KnownSourceEdge> };

export type Background = { "backgroundId": string; "revision": number; "fictional": true; "text": string; "sourceLabel": string; "period": string; "scope": string; "limitations": ReadonlyArray<string> };

export type PlayerStatement = { "statementId": string; "revision": 1; "text": string; "verification": "unverified" };

export type PublicAction = { "actionId": string; "label": string; "description": string; "knownDurationMs": (number | null); "durationQualifier": "base_only" | "range_unknown" | "fixed"; "limitations": ReadonlyArray<string> };

export type ChannelCapability = { "channel": "satellite" | "drone" | "localAgency" | "witness"; "publicTargetIds": ReadonlyArray<string>; "canObserve": ReadonlyArray<string>; "cannotConfirm": ReadonlyArray<string> };

export type Question = { "questionId": string; "kind": "automatic" | "why" | "compare" | "uncertainties" | "next_check" | "free_text"; "text": string; "selectedEvidenceRefs": ReadonlyArray<EvidenceRef> };

export type AdvisorInput = { "schemaVersion": "0.5"; "sessionId": string; "sceneId": "E1" | "E2" | "E3"; "inputHash": string; "contextVersion": number; "publicTask": { "objective": string; "currentNodeId": string; "actions": ReadonlyArray<PublicAction>; "channelCapabilities": ReadonlyArray<ChannelCapability> }; "backgrounds": ReadonlyArray<Background>; "evidence": ReadonlyArray<Evidence>; "statements": ReadonlyArray<PlayerStatement>; "question": Question; "priorAnalysis": ({ "summary": string; "citations": ReadonlyArray<Citation> } | null) };

export type Claim = { "claimId": string; "kind": "evidenceObservation" | "backgroundRecord" | "playerStatement" | "inference"; "text": string; "citations": ReadonlyArray<Citation> };

export type Recommendation = { "actionId": (string | null); "rationale": string; "claimRefs": ReadonlyArray<string>; "conditions": ReadonlyArray<string> };

export type AdvisorOutput = { "sessionId": string; "inputHash": string; "summary": string; "claims": ReadonlyArray<Claim>; "recommendation": Recommendation; "uncertainties": ReadonlyArray<string>; "investigationSuggestions": ReadonlyArray<{ "channel": "satellite" | "drone" | "localAgency" | "witness"; "publicTargetId": string; "questionToResolve": string; "claimRefs": ReadonlyArray<string> }>; "changeSummary": string };

export type BehaviorFact = { "factId": string; "contextId": string; "ruleId": string; "kind": "observation" | "opportunity" | "support" | "counterevidence" | "exclusion" | "coverage"; "text": string; "sourceEventIds": ReadonlyArray<string>; "evidenceRefs": ReadonlyArray<EvidenceRef>; "availableAtMissionMs": number; "cutoffMissionMs": number };

export type BehaviorContext = { "contextId": string; "sceneId": "E1" | "E2" | "E3"; "subjectBindingId": string; "controllerKind": "human"; "kind": "route_decision" | "investigation_request" | "wait"; "cutoffMissionMs": number; "factRefs": ReadonlyArray<string>; "playerVisibleRefs": ReadonlyArray<EvidenceRef>; "advisorUploadedRefs": ReadonlyArray<EvidenceRef>; "displayedAdviceId": (string | null); "displayedAdviceAtMs": (number | null); "chosenActionId": string; "legalActionIds": ReadonlyArray<string>; "visibleCostSummary": string; "reasonCodes": ReadonlyArray<"evidence_supported" | "current_conflict" | "accepted_uncertainty_for_time" | "ai_said_so" | "prior_ai_error_only" | "new_question" | "no_new_question" | "no_reason">; "reasonText": string; "oralKnowledgeStatus": "not_collected" | "self_reported" | "not_applicable"; "technicalLimitations": ReadonlyArray<string> };

export type DimensionBound = { "eligibleOpportunities": number; "eligibleContextRefs": ReadonlyArray<string>; "supportCandidates": ReadonlyArray<{ "contextId": string; "factRefs": ReadonlyArray<string> }>; "counterevidenceRefs": ReadonlyArray<string>; "exclusionRefs": ReadonlyArray<string>; "allowedSupportLevels": ReadonlyArray<"not_assessable" | "not_observed" | "observed_once" | "repeated_observation"> };

export type EvaluatorInput = { "schemaVersion": "0.5"; "sessionId": string; "sealedHash": string; "rubricVersion": "observable-rubric-0.5-review"; "subjectBindingId": string; "contexts": ReadonlyArray<BehaviorContext>; "facts": ReadonlyArray<BehaviorFact>; "bounds": { "complacency": DimensionBound; "distrust": DimensionBound; "overCaution": DimensionBound; "calibratedTrust": DimensionBound }; "allowedOverallPatterns": ReadonlyArray<"mixed" | "limited_pattern" | "insufficient_evidence">; "coverage": { "scenesObserved": ReadonlyArray<"E1" | "E2" | "E3">; "terminalKind": "normal_end" | "abandoned" | "technical_interruption" | "demo"; "limitations": ReadonlyArray<string> } };

export type DimensionResult = { "supportLevel": "not_assessable" | "not_observed" | "observed_once" | "repeated_observation"; "eligibleOpportunities": number; "supportContextRefs": ReadonlyArray<string>; "supportFactRefs": ReadonlyArray<string>; "counterevidenceRefs": ReadonlyArray<string>; "explanation": string; "uncertainties": ReadonlyArray<string> };

export type EvaluatorOutput = { "sessionId": string; "sealedHash": string; "rubricVersion": "observable-rubric-0.5-review"; "summary": string; "overallPattern": "mixed" | "limited_pattern" | "insufficient_evidence"; "dimensions": { "complacency": DimensionResult; "distrust": DimensionResult; "overCaution": DimensionResult; "calibratedTrust": DimensionResult }; "keyMoments": ReadonlyArray<{ "contextId": string; "factRefs": ReadonlyArray<string>; "explanation": string }>; "nextAttempts": ReadonlyArray<{ "suggestion": string; "basisRefs": ReadonlyArray<string> }>; "limitations": ReadonlyArray<string> };

export type AgentJobView = { "jobId": string; "agentRole": "advisor" | "evaluator"; "status": "queued" | "running" | "succeeded" | "fallback" | "failed" | "superseded" | "cancelled"; "mode": "live_model" | "offline_template"; "inputVersion": number; "createdAt": string; "attemptCount": number; "result": (AdvisorOutput | EvaluatorOutput | null); "error": ({ "code": "AGENT_INPUT_INVALID" | "AGENT_INPUT_TOO_LARGE" | "MODEL_NOT_CONFIGURED" | "MODEL_TIMEOUT" | "MODEL_TRANSPORT" | "MODEL_RATE_LIMIT" | "MODEL_INVALID_OUTPUT" | "MODEL_BUDGET_EXHAUSTED" | "CONTEXT_SUPERSEDED" | "SESSION_TERMINAL"; "retryable": boolean } | null) };
