#!/usr/bin/env python3
"""Generate TS wire types from the canonical JSON Schemas; JSON Schema remains authoritative."""
import json
import argparse
from pathlib import Path

HERE=Path(__file__).resolve().parent
ROOT=HERE.parent

def ts(schema,context):
    if '$ref' in schema:
        r=schema['$ref'];name=r.rsplit('/',1)[1]
        if r.startswith('#/'):return name
        if 'agents/contracts.schema.json' in r:return 'Agent.'+name
        if 'public.schema.json' in r:return 'Public.'+name
        raise ValueError('Unknown type ref '+r)
    if 'const'in schema:return json.dumps(schema['const'],ensure_ascii=False)
    if 'enum'in schema:return ' | '.join(json.dumps(x,ensure_ascii=False)for x in schema['enum'])
    typ=schema.get('type')
    if typ=='object' or ('properties'in schema and typ is None):
        props=schema.get('properties',{})
        required=schema.get('required',[])
        return '{ '+ '; '.join(json.dumps(k)+('' if k in required else '?')+': '+ts(v,context)for k,v in props.items())+' }'
    if 'oneOf'in schema or 'anyOf'in schema:return '('+' | '.join(ts(x,context)for x in schema.get('oneOf',schema.get('anyOf')))+')'
    if 'allOf'in schema:return '('+' & '.join(ts(x,context)for x in schema['allOf'])+')'
    if isinstance(typ,list):return '('+' | '.join(ts(dict(schema,type=x),context)for x in typ)+')'
    if typ=='array':return 'ReadonlyArray<'+ts(schema['items'],context)+'>'
    if typ in ['string','boolean','null']:return typ
    if typ in ['integer','number']:return 'number'
    if schema is False:return 'never'
    raise ValueError('Unrepresentable schema '+repr(schema))

def generate():
    outputs={}
    for source,target,header in [
        (ROOT/'agents/contracts.schema.json','agent-derived.types.ts',''),
        (HERE/'public.schema.json','public.types.ts','import type * as Agent from "./agent-derived.types";\n'),
        (HERE/'internal.schema.json','internal.types.ts','import type * as Public from "./public.types";\n'),
    ]:
        data=json.loads(source.read_text())
        text='// GENERATED by contracts/generate_types.py. Do not edit.\n// Runtime constraints and conditional branches are enforced by JSON Schema, not TS.\n'+header+'\n'
        text+='\n'.join('export type '+name+' = '+ts(value,target)+';\n'for name,value in data['$defs'].items())
        outputs[target]=text
    c='// GENERATED from content schemas. Server-only; never import into the browser bundle.\n'
    for source,name in [('policy.schema.json','PrivatePolicy'),('scenario.schema.json','PrivateCampaign')]:
        c+='export type '+name+' = '+ts(json.loads((ROOT/'content'/source).read_text()),name)+';\n'
    outputs['content-derived.types.ts']=c
    return outputs

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,text in generate().items():
        p=HERE/name
        if args.check:
            assert p.exists() and p.read_text()==text, f'{name} differs from schema; regenerate'
        else:p.write_text(text)
    print('TS contract types verified' if args.check else 'TS contract types generated')
