// GENERATED by contracts/generate_types.py. Do not edit.
// Runtime constraints and conditional branches are enforced by JSON Schema, not TS.
import type * as Public from "./public.types";

export type Actor = { "kind": "human" | "npc" | "rules" | "system"; "actorId": (string | null); "role": ("commander" | "analyst" | "liaison" | null) };

export type EventSessionCreated = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "session.created"; "data": { "profileId": "SINGLE_PLAYER_REFERENCE"; "policyHash": string; "contentVersionId": string; "privateCaseId": string; "seedHash": string } };

export type EventSessionStarted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "session.started"; "data": { "missionDeadlineMs": 600000; "startedAt": string } };

export type EventSceneEntered = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "scene.entered"; "data": { "sceneId": "E1" | "E2" | "E3"; "location": Public.KnownLocation } };

export type EventTaskAccepted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "task.accepted"; "data": { "taskId": string; "targetRole": "analyst" | "liaison"; "taskKind": "investigate_and_report" | "request_report"; "topicId": string; "reservationLedgerId": string; "investigationId": (string | null); "reasonAnnotation": (Public.ReasonAnnotation | null) } };

export type EventInvestigationStarted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "investigation.started"; "data": { "investigationId": string; "taskId": string; "channel": "satellite" | "drone" | "localAgency" | "witness"; "targetId": string; "dueAtMissionMs": number; "spendLedgerId": string } };

export type EventInvestigationCompleted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "investigation.completed"; "data": { "investigationId": string; "evidenceInstanceId": string; "revision": number } };

export type EventInvestigationCancelled = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "investigation.cancelled"; "data": { "investigationId": string; "reason": "scene_left" | "session_terminated"; "releaseLedgerId": (string | null) } };

export type EventInvestigationFailed = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "investigation.failed"; "data": { "investigationId": string; "reason": "technical_failure"; "refundLedgerId": string; "releaseLedgerId": string } };

export type EventEvidenceAcquired = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "evidence.acquired"; "data": { "evidenceInstanceId": string; "ownerRole": "analyst" | "liaison"; "revision": number; "definitionId": string; "payloadHash": string } };

export type EventReportCreated = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "report.created"; "data": { "reportId": string; "evidenceInstanceId": string; "revision": number; "sourceRole": "analyst" | "liaison"; "spendLedgerId": string; "selectionRule": "public_topic_priority_then_acquisition" } };

export type EventProvenanceDisclosed = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "provenance.disclosed"; "data": { "disclosureId": string; "evidenceInstanceId": string; "privateEdgeDefinitionIds": ReadonlyArray<string> } };

export type EventUploadCreated = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "upload.created"; "data": { "uploadId": string; "reportId": string; "evidenceInstanceId": string; "revision": number; "inboxVersion": number; "assistantContextVersion": number; "spendLedgerId": string } };

export type EventPlayerStatementCreated = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "player_statement.created"; "data": { "statementId": string; "sceneId": "E1" | "E2" | "E3"; "text": string; "assistantContextVersion": number } };

export type EventAgentJobQueued = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "agent.job_queued"; "data": { "jobId": string; "agentRole": "advisor"; "inputManifestId": string; "sealedHash": null; "inputHash": string; "inputVersion": number } };

export type EventAgentAttemptStarted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "agent.attempt_started"; "data": { "jobId": string; "agentRole": "advisor"; "attemptId": string; "attemptNumber": number; "spendLedgerId": string } };

export type EventAgentJobFinished = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "agent.job_finished"; "data": { "jobId": string; "agentRole": "advisor"; "status": "succeeded" | "fallback" | "failed" | "superseded" | "cancelled"; "outputHash": (string | null) } };

export type EventDisplayReceived = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "display.received"; "data": { "receiptId": string; "observedStateVersion": number; "observedSceneId": ("E1" | "E2" | "E3" | null); "displayKind": "report_opened" | "advice_displayed" | "consequence_seen" | "context_displayed"; "reportId": (string | null); "jobId": (string | null); "operationId": (string | null) } };

export type EventActionCommitted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "action.committed"; "data": { "decisionId": string; "operationId": string; "sceneId": "E1" | "E2" | "E3"; "actionId": string; "reason": string; "reasonAnnotation": (Public.ReasonAnnotation | null); "referencedReportIds": ReadonlyArray<string>; "basedOnAdviceJobId": (string | null); "cancelledInvestigationIds": ReadonlyArray<string> } };

export type EventOperationSegmentCompleted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "operation.segment_completed"; "data": { "operationId": string; "segmentId": string; "location": Public.KnownLocation; "actualDurationMs": number; "releasedEvidenceIds": ReadonlyArray<string> } };

export type EventOperationFinished = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "operation.finished"; "data": { "operationId": string; "status": "completed" | "cancelled" | "failed"; "reason": "normal" | "mission_deadline" | "abandoned" | "technical_failure" } };

export type EventQuotaChanged = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "quota.changed"; "data": { "ledgerId": string; "accountId": string; "unit": "investigation" | "report" | "upload" | "model_call"; "entryKind": "reserve" | "spend" | "release" | "refund"; "quantity": number; "remainingAfter": number; "reservedAfter": number; "causationId": string } };

export type EventHandoffTaskCompleted = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "handoff.task_completed"; "data": { "task": "manifest" | "inspection"; "nodeId": "N10" | "N07"; "operationId": string } };

export type EventMedicalTargetMissed = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "medical.target_missed"; "data": { "targetAtMissionMs": number; "stateAfter": "target_missed" } };

export type EventSessionSealed = { "eventId": string; "sessionId": string; "seq": number; "missionTimeMs": number; "recordedAt": string; "actor": Actor; "requestId": (string | null); "causationEventId": (string | null); "eventType": "session.sealed"; "data": { "sealedHash": string; "outcome": Public.OutcomeView } };

export type InternalEvent = (EventSessionCreated | EventSessionStarted | EventSceneEntered | EventTaskAccepted | EventInvestigationStarted | EventInvestigationCompleted | EventInvestigationCancelled | EventInvestigationFailed | EventEvidenceAcquired | EventReportCreated | EventProvenanceDisclosed | EventUploadCreated | EventPlayerStatementCreated | EventAgentJobQueued | EventAgentAttemptStarted | EventAgentJobFinished | EventDisplayReceived | EventActionCommitted | EventOperationSegmentCompleted | EventOperationFinished | EventQuotaChanged | EventHandoffTaskCompleted | EventMedicalTargetMissed | EventSessionSealed);

export type AuditBehaviorFactsBuilt = { "auditId": string; "sessionId": string; "sealedHash": string; "createdAt": string; "eventType": "behavior.facts_built"; "data": { "factSetHash": string; "factIds": ReadonlyArray<string>; "evaluationConfigId": "EVALUATION_REFERENCE_V1" } };

export type AuditEvaluatorJobQueued = { "auditId": string; "sessionId": string; "sealedHash": string; "createdAt": string; "eventType": "evaluator.job_queued"; "data": { "jobId": string; "agentRole": "evaluator"; "inputHash": string; "inputVersion": number; "evaluationConfigId": "EVALUATION_REFERENCE_V1" } };

export type AuditEvaluatorAttemptStarted = { "auditId": string; "sessionId": string; "sealedHash": string; "createdAt": string; "eventType": "evaluator.attempt_started"; "data": { "jobId": string; "agentRole": "evaluator"; "attemptId": string; "attemptNumber": number } };

export type AuditEvaluatorAttemptFinished = { "auditId": string; "sessionId": string; "sealedHash": string; "createdAt": string; "eventType": "evaluator.attempt_finished"; "data": { "jobId": string; "agentRole": "evaluator"; "attemptId": string; "attemptNumber": number; "status": "succeeded" | "failed" | "timeout" | "unknown"; "inputTokens": (number | null); "outputTokens": (number | null); "providerRequestId": (string | null); "errorCode": ("MODEL_TIMEOUT" | "MODEL_TRANSPORT" | "MODEL_RATE_LIMIT" | "MODEL_INVALID_OUTPUT" | null) } };

export type AuditEvaluatorJobFinished = { "auditId": string; "sessionId": string; "sealedHash": string; "createdAt": string; "eventType": "evaluator.job_finished"; "data": { "jobId": string; "agentRole": "evaluator"; "status": "succeeded" | "fallback" | "failed" | "cancelled"; "outputHash": (string | null) } };

export type AuditExportQueued = { "auditId": string; "sessionId": string; "sealedHash": string; "createdAt": string; "eventType": "export.queued"; "data": { "exportId": string; "includePlayerStatements": boolean } };

export type AuditExportFinished = { "auditId": string; "sessionId": string; "sealedHash": string; "createdAt": string; "eventType": "export.finished"; "data": { "exportId": string; "status": "succeeded" | "failed"; "artifactHash": (string | null); "errorCode": ("storage_unavailable" | "export_size_limit" | null) } };

export type PostgameAuditEvent = (AuditBehaviorFactsBuilt | AuditEvaluatorJobQueued | AuditEvaluatorAttemptStarted | AuditEvaluatorAttemptFinished | AuditEvaluatorJobFinished | AuditExportQueued | AuditExportFinished);

export type CommandRecord = { "commandId": string; "requestId": string; "launchId": string; "sessionId": (string | null); "runEpoch": (string | null); "idempotencyKey": string; "method": "POST"; "path": string; "requestHash": string; "status": "accepted" | "completed" | "rejected"; "httpStatus": number; "responseKind": "session" | "task" | "upload" | "question" | "action" | "receipt" | "outcome" | "evaluation" | "export" | "problem"; "responseJsonHash": string; "committedAt": string };

export type InvestigationRecord = { "investigationId": string; "taskId": string; "sessionId": string; "sceneId": "E1" | "E2" | "E3"; "targetRole": "analyst" | "liaison"; "channel": "satellite" | "drone" | "localAgency" | "witness"; "investigationKind": "satellite_scan" | "drone_observe" | "agency_contact" | "witness_interview" | "provenance_trace"; "targetId": string; "topicId": string; "sourceReportId": (string | null); "status": "queued" | "running" | "completed" | "cancelled" | "failed"; "acceptedAtMissionMs": number; "dueAtMissionMs": number; "completedAtMissionMs": (number | null); "reservedReportLedgerId": string; "spendLedgerId": string; "resultEvidenceInstanceId": (string | null) };

export type QuotaEntry = { "ledgerId": string; "sessionId": string; "sceneId": ("E1" | "E2" | "E3" | null); "ownerRole": "analyst" | "liaison" | "commander" | "advisor" | "evaluator"; "unit": "investigation" | "report" | "upload" | "model_call"; "channel": ("satellite" | "drone" | "localAgency" | "witness" | null); "entryKind": "reserve" | "spend" | "release" | "refund"; "quantity": number; "causationId": string; "createdAtMissionMs": number };

export type CommandSuccess = (Public.SessionCreated | Public.SessionProjection | Public.TaskAccepted | Public.UploadView | Public.QuestionAccepted | Public.ActionAccepted | Public.ReceiptView | Public.OutcomeView | Public.EvaluationAccepted | Public.ExportAccepted);
