// GENERATED by contracts/generate_types.py. Do not edit.
// Runtime constraints and conditional branches are enforced by JSON Schema, not TS.
import type * as Agent from "./agent-derived.types";

export type Uuid = string;

export type Sha256 = string;

export type SceneId = "E1" | "E2" | "E3";

export type MissionMs = number;

export type AdvisorJobView = (Agent.AgentJobView & { "agentRole"?: "advisor" });

export type EvaluationJobView = (Agent.AgentJobView & { "agentRole"?: "evaluator" });

export type ErrorCode = "INVALID_REQUEST" | "UNAUTHORIZED" | "CAPABILITY_DENIED" | "RESOURCE_NOT_FOUND" | "STATE_VERSION_CONFLICT" | "SCENE_CONFLICT" | "RUN_EPOCH_CONFLICT" | "IDEMPOTENCY_KEY_REUSED" | "PHASE_NOT_ALLOWED" | "POLICY_NOT_APPROVED" | "BUDGET_EXHAUSTED" | "ROLE_BUSY" | "TARGET_NOT_AVAILABLE" | "REPORT_LIMIT" | "UPLOAD_LIMIT" | "REVISION_CONFLICT" | "NOT_REPORTED" | "ACTION_NOT_AVAILABLE" | "SEALED_HASH_MISMATCH" | "NOT_TERMINAL" | "ALREADY_TERMINAL" | "CURSOR_EXPIRED" | "CURSOR_SCOPE_MISMATCH" | "RATE_LIMITED" | "MODEL_BUDGET_EXHAUSTED" | "BODY_TOO_LARGE" | "STORAGE_UNAVAILABLE" | "SERVICE_UNAVAILABLE";

export type Problem = { "type": string; "title": string; "status": number; "code": ErrorCode; "requestId": string; "retryable": boolean; "currentStateVersion": (number | null); "detail": string; "violations": ReadonlyArray<{ "path": string; "reason": "required" | "format" | "range" | "unknown_property" | "invalid_combination" | "not_allowed" }> };

export type Problem400 = (Problem & { "status"?: 400; "code"?: "INVALID_REQUEST" });

export type Problem401 = (Problem & { "status"?: 401; "code"?: "UNAUTHORIZED" });

export type Problem403 = (Problem & { "status"?: 403; "code"?: "CAPABILITY_DENIED" | "CURSOR_SCOPE_MISMATCH" });

export type Problem404 = (Problem & { "status"?: 404; "code"?: "RESOURCE_NOT_FOUND" });

export type Problem409 = (Problem & { "status"?: 409; "code"?: "STATE_VERSION_CONFLICT" | "SCENE_CONFLICT" | "RUN_EPOCH_CONFLICT" | "IDEMPOTENCY_KEY_REUSED" | "REVISION_CONFLICT" });

export type Problem410 = (Problem & { "status"?: 410; "code"?: "CURSOR_EXPIRED" });

export type Problem413 = (Problem & { "status"?: 413; "code"?: "BODY_TOO_LARGE" });

export type Problem422 = (Problem & { "status"?: 422; "code"?: "PHASE_NOT_ALLOWED" | "POLICY_NOT_APPROVED" | "BUDGET_EXHAUSTED" | "ROLE_BUSY" | "TARGET_NOT_AVAILABLE" | "REPORT_LIMIT" | "UPLOAD_LIMIT" | "NOT_REPORTED" | "ACTION_NOT_AVAILABLE" | "SEALED_HASH_MISMATCH" | "NOT_TERMINAL" | "ALREADY_TERMINAL" });

export type Problem429 = (Problem & { "status"?: 429; "code"?: "RATE_LIMITED" | "MODEL_BUDGET_EXHAUSTED" });

export type Problem503 = (Problem & { "status"?: 503; "code"?: "STORAGE_UNAVAILABLE" | "SERVICE_UNAVAILABLE" });

export type HealthView = { "status": "ok" | "degraded"; "apiVersion": "v1"; "contractVersion": "0.5"; "storageReady": boolean; "modelConfigured": boolean };

export type ProfileSummary = { "profileId": "SINGLE_PLAYER_REFERENCE"; "status": "review" | "approved"; "mode": "single_player"; "normalStartAllowed": boolean; "designPreviewAllowed": boolean; "policyHash": string; "contentVersionId": string; "description": string };

export type BootstrapView = { "launchId": string; "apiVersion": "v1"; "contractVersion": "0.5"; "capabilities": ReadonlyArray<"commander.read" | "session.create" | "session.command" | "evaluation.request" | "export.request">; "profiles": ReadonlyArray<ProfileSummary>; "maximumRequestBytes": 65536; "sseReconnectMs": 2000; "defaultLocale"?: "en-US" | "zh-CN"; "supportedLocales"?: ReadonlyArray<"en-US" | "zh-CN"> };

export type CreateSessionRequest = { "profileId": "SINGLE_PLAYER_REFERENCE"; "runPurpose": "approved_play" | "design_preview"; "locale": "zh-CN" | "en-US"; "contentVersionId": string };

export type KnownLocation = { "nodeId": (string | null); "routeId": (string | null); "progressPermille": number };

export type ResourceBalance = { "role": "analyst" | "liaison"; "channel": "satellite" | "drone" | "localAgency" | "witness"; "initial": number; "remaining": number; "spent": number; "scope": "session" };

export type ReportQuota = { "role": "analyst" | "liaison"; "sceneId": "E1" | "E2" | "E3"; "limit": 3; "used": number; "reserved": number; "remaining": number };

export type UploadQuota = { "sceneId": "E1" | "E2" | "E3"; "mode": "cumulative"; "limit": 5; "used": number; "remaining": number };

export type MedicalView = { "status": "stable" | "support_needed" | "target_missed"; "targetAtMissionMs": (number | null); "note": string };

export type PendingTasks = { "manifest": "notRequired" | "pending" | "completed"; "inspection": "notRequired" | "pending" | "completed" };

export type PublicCost = { "knownDurationMs": (number | null); "uncertainty": "none" | "possible_delay" | "duration_unknown"; "description": string };

export type TaskOption = { "targetId": string; "topicId": string; "targetRole": "analyst" | "liaison"; "label": string; "investigationKind": "satellite_scan" | "drone_observe" | "agency_contact" | "witness_interview" | "provenance_trace"; "resourceChannel": "satellite" | "drone" | "localAgency" | "witness"; "cost": PublicCost; "available": boolean; "disabledReason": ("no_resource" | "no_report_slot" | "role_busy" | "phase_locked" | "needs_report_reference" | null) };

export type ReasonAnnotation = { "reasonCodes": ReadonlyArray<"evidence_supported" | "current_conflict" | "accepted_uncertainty_for_time" | "ai_said_so" | "prior_ai_error_only" | "new_question" | "no_new_question">; "acknowledgedLimitation": boolean; "comparedKnownCosts": boolean; "declaredQuestionKey": (string | null) };

export type ActionOption = { "actionId": string; "label": string; "kind": "route" | "wait" | "terminal_wait"; "knownRouteIds": ReadonlyArray<string>; "cost": PublicCost; "knownRisk": string; "irreversibleNotice": (string | null); "available": boolean; "disabledReason": ("phase_locked" | "not_at_origin" | "already_selected" | "recovery_used" | null) };

export type EvidenceCard = { "evidenceInstanceId": string; "definitionId": string; "revision": number; "sceneId": "E1" | "E2" | "E3"; "title": string; "body": string; "statementKind": "observation" | "testimony" | "provenance" | "correction" | "brief"; "sourceLabel": string; "channel": "satellite" | "drone" | "localAgency" | "witness" | "initial" | "route_observation"; "observedAt": (string | null); "receivedAtMissionMs": number; "validUntilMissionMs": (number | null); "freshness": "current" | "historical" | "superseded" | "unknown"; "observationScope": string; "provenanceStatus": "unverified" | "partially_verified" | "verified"; "supersedesEvidenceInstanceId": (string | null) };

export type ReportView = { "reportId": string; "evidenceInstanceId": string; "revision": number; "sourceRole": "analyst" | "liaison"; "sceneId": "E1" | "E2" | "E3"; "reportedAtMissionMs": number; "card": EvidenceCard };

export type UploadItem = { "reportId": string; "expectedRevision": number };

export type UploadSnapshot = { "uploadId": string; "reportId": string; "evidenceInstanceId": string; "revision": number; "sceneId": "E1" | "E2" | "E3"; "uploadedAtMissionMs": number; "payloadHash": string };

export type UploadView = { "sessionId": string; "stateVersion": number; "inboxVersion": number; "assistantContextVersion": number; "added": ReadonlyArray<UploadSnapshot>; "currentSceneUploads": ReadonlyArray<UploadSnapshot>; "quota": UploadQuota; "analysisJobId": (string | null) };

export type TaskView = { "taskId": string; "sessionId": string; "sceneId": "E1" | "E2" | "E3"; "targetRole": "analyst" | "liaison"; "taskKind": "investigate_and_report" | "request_report"; "topicId": string; "resourceChannel": ("satellite" | "drone" | "localAgency" | "witness" | null); "status": "accepted" | "running" | "completed" | "cancelled" | "failed"; "investigationId": (string | null); "reportId": (string | null); "createdAt": string; "completedAt": (string | null); "failureCode": ("scene_left" | "session_terminated" | "technical_failure" | "no_matching_acquired_report" | null) };

export type OperationView = { "operationId": string; "sessionId": string; "sceneId": "E1" | "E2" | "E3"; "operationKind": "action" | "wait"; "actionId": string; "status": "accepted" | "running" | "completed" | "cancelled" | "failed"; "createdAt": string; "completedAt": (string | null); "currentLocation": KnownLocation; "publicProgressLabel": string; "failureCode": ("mission_deadline" | "abandoned" | "technical_failure" | null) };

export type ReceiptView = { "receiptId": string; "accepted": true; "stateVersion": number };

export type ProvenanceNode = { "nodeId": string; "kind": "report" | "declared_source" | "verified_source"; "label": string; "reportId": (string | null) };

export type ProvenanceEdge = { "edgeId": string; "fromNodeId": string; "toNodeId": string; "relation": "cites" | "reports" | "same_origin"; "status": "claimed" | "hypothesized" | "verified"; "disclosedByReportId": (string | null) };

export type ProvenanceView = { "sessionId": string; "sceneId": "E1" | "E2" | "E3"; "stateVersion": number; "nodes": ReadonlyArray<ProvenanceNode>; "edges": ReadonlyArray<ProvenanceEdge>; "notice": string };

export type OutcomeView = { "sessionId": string; "runEpoch": string; "sealedHash": string; "sealedAt": string; "sealedAtMissionMs": number; "taskSuccess": boolean; "terminationReason": "arrived" | "mission_deadline" | "awaiting_transfer" | "abandoned" | "technical_interruption"; "arrivedAtMissionMs": (number | null); "handoffCompletedAtMissionMs": (number | null); "pendingTasks": PendingTasks; "finalLocation": KnownLocation; "civilianCount": 20; "medical": MedicalView; "routeIdsTaken": ReadonlyArray<string>; "summary": string };

export type PlayerStatementView = { "statementId": string; "sceneId": "E1" | "E2" | "E3"; "text": string; "sentAtMissionMs": number; "trustStatus": "unverified_player_statement" };

export type PublicLogEntry = { "logId": string; "sequence": number; "missionTimeMs": number; "kind": "brief" | "task_requested" | "report_received" | "uploaded" | "advice_displayed" | "action_committed" | "consequence" | "sealed"; "actor": "player" | "npc" | "rules" | "assistant" | "system"; "summary": string; "reportIds": ReadonlyArray<string>; "jobId": (string | null) };

export type DecisionReplay = { "decisionId": string; "sceneId": "E1" | "E2" | "E3"; "committedAtMissionMs": number; "actionId": string; "reason": string; "reasonAnnotation": (ReasonAnnotation | null); "knownReportIds": ReadonlyArray<string>; "viewedReportIds": ReadonlyArray<string>; "uploadedIds": ReadonlyArray<string>; "displayedAdviceJobIds": ReadonlyArray<string>; "legalActionIds": ReadonlyArray<string>; "knownCosts": ReadonlyArray<{ "actionId": string; "cost": PublicCost }>; "resultSummary": string; "unobservedCommunication": "not_observable" };

export type ReplayView = { "sessionId": string; "sealedHash": string; "decisions": ReadonlyArray<DecisionReplay>; "reports": ReadonlyArray<ReportView>; "playerStatements": ReadonlyArray<PlayerStatementView>; "publicLog": ReadonlyArray<PublicLogEntry>; "nextCursor": (string | null) };

export type ExportArtifact = { "format": "last-mile-review-json"; "formatVersion": "0.5"; "outcome": OutcomeView; "replayPages": ReadonlyArray<ReplayView>; "includedPlayerStatements": boolean; "generatedAt": string; "evaluationJob": (EvaluationJobView | null) };

export type ExportView = { "exportId": string; "sessionId": string; "sealedHash": string; "status": "queued" | "running" | "succeeded" | "failed"; "createdAt": string; "completedAt": (string | null); "artifact": (ExportArtifact | null); "errorCode": ("storage_unavailable" | "export_size_limit" | null) };

export type SessionProjection = { "sessionId": string; "runEpoch": string; "profileId": "SINGLE_PLAYER_REFERENCE"; "runPurpose": "approved_play" | "design_preview"; "policyHash": string; "contentVersionId": string; "stateVersion": number; "lifecycle": "created" | "active" | "sealed"; "phase": "briefing" | "scene" | "resolving" | "terminal"; "sceneId": ("E1" | "E2" | "E3" | null); "missionTimeMs": number; "missionDeadlineMs": 600000; "serverNow": string; "location": KnownLocation; "civilianCount": 20; "medical": MedicalView; "pendingTasks": PendingTasks; "resources": ReadonlyArray<ResourceBalance>; "reportQuotas": ReadonlyArray<ReportQuota>; "uploadQuota": (UploadQuota | null); "reports": ReadonlyArray<ReportView>; "sceneUploads": ReadonlyArray<UploadSnapshot>; "inboxVersion": number; "assistantContextVersion": number; "activeTasks": ReadonlyArray<TaskView>; "activeOperation": (OperationView | null); "taskOptions": ReadonlyArray<TaskOption>; "actionOptions": ReadonlyArray<ActionOption>; "latestAdviceJob": (AdvisorJobView | null); "unuploadedReportIds": ReadonlyArray<string>; "lastViewCursor": string; "sealedHash": (string | null); "locale"?: "en-US" | "zh-CN" };

export type SessionCreated = { "sessionId": string; "runEpoch": string; "location": string; "projection": SessionProjection };

export type StartRequest = { "expectedStateVersion": number; "expectedSceneId": null; "payload": { "acknowledgeDesignPreview": boolean } };

export type TaskRequest = { "expectedStateVersion": number; "expectedSceneId": "E1" | "E2" | "E3"; "payload": ({ "taskKind": "investigate_and_report"; "targetRole": "analyst" | "liaison"; "topicId": string; "targetId": string; "investigationKind": "satellite_scan" | "drone_observe" | "agency_contact" | "witness_interview" | "provenance_trace"; "sourceReportId": (string | null); "reasonAnnotation": (ReasonAnnotation | null) } | { "taskKind": "request_report"; "targetRole": "analyst" | "liaison"; "topicId": string }) };

export type UploadRequest = { "expectedStateVersion": number; "expectedSceneId": "E1" | "E2" | "E3"; "payload": { "items": ReadonlyArray<UploadItem> } };

export type QuestionRequest = { "expectedStateVersion": number; "expectedSceneId": "E1" | "E2" | "E3"; "payload": { "questionKind": "explain_basis" | "compare_routes" | "uncertainties" | "next_information" | "free_text"; "text": (string | null); "expectedInboxVersion": number; "uploadBatch": ReadonlyArray<UploadItem> } };

export type ActionRequest = { "expectedStateVersion": number; "expectedSceneId": "E1" | "E2" | "E3"; "payload": { "actionId": string; "waitDurationMs": (15000 | 30000 | 60000 | null); "reason": string; "reasonAnnotation": (ReasonAnnotation | null); "basedOnAdviceJobId": (string | null); "referencedReportIds": ReadonlyArray<string>; "cancelPendingInvestigations": boolean } };

export type DisplayReceiptRequest = { "observedStateVersion": number; "observedSceneId": ("E1" | "E2" | "E3" | null); "payload": { "displayKind": "report_opened" | "advice_displayed" | "consequence_seen" | "context_displayed"; "reportId": (string | null); "jobId": (string | null); "operationId": (string | null) } };

export type AbandonRequest = { "expectedStateVersion": number; "expectedSceneId": ("E1" | "E2" | "E3" | null); "payload": { "reason": "player_exit" | "restart_requested" } };

export type EvaluationRequest = { "sealedHash": string; "evaluationConfigId": "EVALUATION_REFERENCE_V1" };

export type ExportRequest = { "sealedHash": string; "format": "last-mile-review-json"; "includePlayerStatements": boolean };

export type TaskAccepted = { "requestId": string; "stateVersion": number; "task": TaskView; "operationLocation": string; "reservedReportSlots": number };

export type ActionAccepted = { "requestId": string; "stateVersion": number; "operation": OperationView; "operationLocation": string };

export type QuestionAccepted = { "requestId": string; "stateVersion": number; "inboxVersion": number; "assistantContextVersion": number; "job": AdvisorJobView; "operationLocation": string };

export type EvaluationAccepted = { "requestId": string; "sealedHash": string; "job": EvaluationJobView; "operationLocation": string };

export type ExportAccepted = { "requestId": string; "export": ExportView; "operationLocation": string };

export type SseProjectionChanged = { "eventType": "projection.changed"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": SessionProjection };

export type SseTaskUpdated = { "eventType": "task.updated"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": TaskView };

export type SseReportReceived = { "eventType": "report.received"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": ReportView };

export type SseUploadsChanged = { "eventType": "uploads.changed"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": UploadView };

export type SseAdviceUpdated = { "eventType": "advice.updated"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": AdvisorJobView };

export type SseOperationUpdated = { "eventType": "operation.updated"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": OperationView };

export type SseOutcomeSealed = { "eventType": "outcome.sealed"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": OutcomeView };

export type SseEvaluationUpdated = { "eventType": "evaluation.updated"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": EvaluationJobView };

export type SseExportUpdated = { "eventType": "export.updated"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": ExportView };

export type SseClockSample = { "eventType": "clock.sample"; "sessionId": string; "runEpoch": string; "viewSequence": number; "stateVersion": number; "data": { "missionTimeMs": number; "serverNow": string; "missionDeadlineMs": 600000; "location"?: KnownLocation } };

export type PublicSseEvent = (SseProjectionChanged | SseTaskUpdated | SseReportReceived | SseUploadsChanged | SseAdviceUpdated | SseOperationUpdated | SseOutcomeSealed | SseEvaluationUpdated | SseExportUpdated | SseClockSample);
